import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { createTask, getTasks, deleteTask, generateTaskAI } from '../api';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { 
    Plus, Briefcase, Clock, Users, Trash2, X, 
    ClipboardList, ChevronRight, Eye, Code, FileText, Sparkles
} from 'lucide-react';

export default function EmployerTasks() {
    const { user } = useAuth();
    const [tasks, setTasks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showCreate, setShowCreate] = useState(false);
    const [form, setForm] = useState({
        skillName: 'React Frontend Development',
        title: '',
        description: '',
        questions: [''],
        timeLimitMinutes: 30
    });
    const [submitting, setSubmitting] = useState(false);
    const [creationMode, setCreationMode] = useState('manual'); // 'manual' | 'ai'

    const skillOptions = [
        'React Frontend Development', 'Node.js API Development',
        'JavaScript Debugging', 'SQL Database Querying',
        'Python Scripting', 'DevOps / Docker', 'C++ Scripting'
    ];

    const fetchTasks = async () => {
        try {
            const { data } = await getTasks({ employerId: user.id });
            setTasks(data);
        } catch (err) {
            console.error('Failed to fetch data:', err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { fetchTasks(); }, []);

    const handleAddQuestion = () => {
        setForm(prev => ({ ...prev, questions: [...prev.questions, ''] }));
    };

    const handleQuestionChange = (index, value) => {
        const updated = [...form.questions];
        updated[index] = value;
        setForm(prev => ({ ...prev, questions: updated }));
    };

    const handleRemoveQuestion = (index) => {
        setForm(prev => ({
            ...prev,
            questions: prev.questions.filter((_, i) => i !== index)
        }));
    };

    const handleAIGenerate = async () => {
        if (!form.skillName) return toast.error('Please select a skill first');
        
        setGenerating(true);
        const toastId = toast.loading('Gemini is generating your assessment...');
        
        try {
            const { data } = await generateTaskAI({
                skillName: form.skillName,
                timeLimitMinutes: form.timeLimitMinutes
            });
            
            setForm(prev => ({
                ...prev,
                title: data.task.title,
                description: data.task.description,
                questions: data.task.questions
            }));
            
            toast.success('Task generated by AI!', { id: toastId });
        } catch (err) {
            console.error('AI Generation failed:', err);
            toast.error(err.response?.data?.message || 'Failed to generate task via AI', { id: toastId });
        } finally {
            setGenerating(false);
        }
    };



    const handleCreate = async (e) => {
        e.preventDefault();
        if (!form.title.trim()) return toast.error('Title is required');
        if (form.questions.filter(q => q.trim()).length === 0) return toast.error('Add at least one question');

        setSubmitting(true);
        try {
            await createTask({
                ...form,
                questions: form.questions.filter(q => q.trim())
            });
            toast.success('Task created!');
            setShowCreate(false);
            setForm({ skillName: 'React Frontend Development', title: '', description: '', questions: [''], timeLimitMinutes: 30 });
            setSelectedCandidateId('');
            setSelectedSkills([]);
            fetchTasks();
        } catch (err) {
            toast.error(err.response?.data?.message || 'Failed to create task');
        } finally {
            setSubmitting(false);
        }
    };

    const handleDelete = async (taskId) => {
        if (!window.confirm('Delete this task?')) return;
        try {
            await deleteTask(taskId);
            toast.success('Task deleted');
            fetchTasks();
        } catch (err) {
            toast.error('Failed to delete task');
        }
    };

    return (
        <div className="dashboard" id="employer-tasks-page">
            <div className="dashboard-header">
                <h1 style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <ClipboardList size={28} /> Skill Assessments
                </h1>
                <p>Create and manage skill-based assessments for candidates</p>
            </div>

            <button 
                className="btn btn-primary" 
                onClick={() => setShowCreate(!showCreate)}
                style={{ marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '8px' }}
                id="create-task-btn"
            >
                {showCreate ? <X size={18} /> : <Plus size={18} />}
                {showCreate ? 'Cancel' : 'Create New Assessment'}
            </button>

            {/* Create Task Form */}
            {showCreate && (
                <div className="task-create-form" id="task-create-form">
                    <h3 style={{ marginBottom: '1.5rem', fontFamily: 'var(--font-display)', fontSize: '1.2rem' }}>
                        <FileText size={18} style={{ verticalAlign: 'middle', marginRight: '8px' }} />
                        New Skill Assessment
                    </h3>
                    <form onSubmit={handleCreate}>
                        <div className="form-group">
                            <label htmlFor="task-title">Assessment Title</label>
                            <input
                                id="task-title"
                                className="form-input"
                                type="text"
                                placeholder="e.g. Build a Todo App Component"
                                value={form.title}
                                onChange={e => setForm(prev => ({ ...prev, title: e.target.value }))}
                                required
                            />
                        </div>

                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                            <div className="form-group">
                                <label htmlFor="task-skill">Skill Category</label>
                                <select
                                    id="task-skill"
                                    className="form-select"
                                    value={form.skillName}
                                    onChange={e => setForm(prev => ({ ...prev, skillName: e.target.value }))}
                                >
                                    {skillOptions.map(s => (
                                        <option key={s} value={s}>{s}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="form-group">
                                <label htmlFor="task-time">Time Limit (minutes)</label>
                                <input
                                    id="task-time"
                                    className="form-input"
                                    type="number"
                                    min="5"
                                    max="120"
                                    value={form.timeLimitMinutes}
                                    onChange={e => setForm(prev => ({ ...prev, timeLimitMinutes: parseInt(e.target.value) || 30 }))}
                                />
                            </div>
                        </div>

                        {/* Mode Selection Choice */}
                        <div style={{ 
                            display: 'flex', 
                            gap: '1rem', 
                            marginBottom: '2rem',
                            padding: '4px',
                            background: 'rgba(255,255,255,0.05)',
                            borderRadius: '12px',
                            border: '1px solid var(--border-color)'
                        }}>
                            <button 
                                type="button"
                                className={`btn ${creationMode === 'manual' ? 'btn-primary' : ''}`}
                                onClick={() => setCreationMode('manual')}
                                style={{ flex: 1, border: 'none', background: creationMode === 'manual' ? 'var(--accent-primary)' : 'transparent' }}
                            >
                                <Code size={16} style={{ marginRight: '8px' }} /> Manual Entry
                            </button>
                            <button 
                                type="button"
                                className={`btn ${creationMode === 'ai' ? 'btn-primary' : ''}`}
                                onClick={() => {
                                    setCreationMode('ai');
                                    if (!form.title && !form.description) handleAIGenerate();
                                }}
                                style={{ flex: 1, border: 'none', background: creationMode === 'ai' ? 'var(--accent-primary)' : 'transparent' }}
                            >
                                <Sparkles size={16} style={{ marginRight: '8px' }} /> Standard AI
                            </button>
                        </div>

                        {creationMode === 'ai' && (
                            <div style={{ 
                                marginBottom: '2rem', 
                                padding: '1.25rem', 
                                background: 'rgba(99, 102, 241, 0.05)', 
                                border: '1px dashed rgba(99, 102, 241, 0.3)',
                                borderRadius: '12px',
                                display: 'flex',
                                justifyContent: 'space-between',
                                alignItems: 'center'
                            }}>
                                <div>
                                    <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--accent-primary)', marginBottom: '4px' }}>
                                        <Sparkles size={16} /> AI Task Designer
                                    </h4>
                                    <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', margin: 0 }}>
                                        Regenerate or refine this assessment using Gemini.
                                    </p>
                                </div>
                                <button 
                                    type="button" 
                                    className="btn btn-secondary btn-sm"
                                    onClick={handleAIGenerate}
                                    disabled={generating || submitting}
                                >
                                    {generating ? 'Generating...' : 'Regenerate'}
                                </button>
                            </div>
                        )}



                        <div className="form-group">
                            <label htmlFor="task-description">Description / Instructions</label>
                            <textarea
                                id="task-description"
                                className="form-input"
                                placeholder="Describe what the candidate should build or demonstrate..."
                                value={form.description}
                                onChange={e => setForm(prev => ({ ...prev, description: e.target.value }))}
                                rows={3}
                                style={{ resize: 'vertical' }}
                            />
                        </div>

                        <div className="form-group">
                            <label>Questions / Tasks</label>
                            {form.questions.map((q, i) => (
                                <div key={i} style={{ display: 'flex', gap: '8px', marginBottom: '8px' }}>
                                    <input
                                        className="form-input"
                                        placeholder={`Question ${i + 1}`}
                                        value={q}
                                        onChange={e => handleQuestionChange(i, e.target.value)}
                                        style={{ flex: 1 }}
                                    />
                                    {form.questions.length > 1 && (
                                        <button type="button" className="btn btn-danger btn-sm" onClick={() => handleRemoveQuestion(i)}>
                                            <Trash2 size={14} />
                                        </button>
                                    )}
                                </div>
                            ))}
                            <button type="button" className="btn btn-secondary btn-sm" onClick={handleAddQuestion} style={{ marginTop: '4px' }}>
                                <Plus size={14} /> Add Question
                            </button>
                        </div>

                        <button type="submit" className="btn btn-gold" disabled={submitting} id="submit-task-btn">
                            {submitting ? 'Creating...' : 'Create Assessment'}
                        </button>
                    </form>
                </div>
            )}

            {/* Task List */}
            {loading ? (
                <div className="loading-container" style={{ minHeight: '20vh' }}>
                    <div className="spinner"></div>
                    <p className="loading-text">Loading assessments...</p>
                </div>
            ) : tasks.length === 0 ? (
                <div className="empty-state">
                    <div className="icon"><Briefcase size={48} /></div>
                    <h3>No assessments yet</h3>
                    <p>Create your first skill assessment to start evaluating candidates</p>
                </div>
            ) : (
                <div className="dashboard-grid">
                    {tasks.map(task => (
                        <div className="task-card" key={task._id} id={`task-${task._id}`}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>
                                <div>
                                    <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '4px' }}>{task.title}</h3>
                                    <span className="skill-tag">{task.skillName}</span>
                                </div>
                                <button className="btn btn-danger btn-sm" onClick={() => handleDelete(task._id)} style={{ padding: '6px 8px' }}>
                                    <Trash2 size={14} />
                                </button>
                            </div>

                            {task.description && (
                                <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '0.75rem', lineHeight: 1.5 }}>
                                    {task.description.substring(0, 120)}{task.description.length > 120 ? '...' : ''}
                                </p>
                            )}

                            <div style={{ display: 'flex', gap: '1rem', fontSize: '0.82rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                    <Clock size={14} /> {task.timeLimitMinutes} min
                                </span>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                    <Code size={14} /> {task.questions?.length || 0} questions
                                </span>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                    <Users size={14} /> {task.submissionCount || 0} submissions
                                </span>
                            </div>

                            <Link 
                                to={`/employer/tasks/${task._id}/submissions`} 
                                className="btn btn-primary btn-sm"
                                style={{ width: '100%', justifyContent: 'center', display: 'flex', alignItems: 'center', gap: '6px' }}
                            >
                                <Eye size={14} /> View Submissions <ChevronRight size={14} />
                            </Link>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
